version: '3'
networks:
  overlay_test:
    driver: overlay

services:
  service1:
    image: busybox
    command: '/bin/ash -c "sleep 1; while true; do ping -c 1 service2; sleep 2; done"'
    networks:
      - overlay_test
  service2:
    image: busybox
    command: '/bin/ash -c "sleep 2; while true; do ping -c 1 service1; sleep 2; done"'
    networks:
      - overlay_test
  service3:
    image: busybox
    command: '/bin/ash -c "sleep 3; while true; do ping -c 1 service4; sleep 2; done"'
    networks:
      - overlay_test
  service4:
    image: busybox
    command: '/bin/ash -c "sleep 4; while true; do ping -c 1 service3; sleep 2; done"'
    networks:
      - overlay_test
  service5:
    image: busybox
    command: '/bin/ash -c "sleep 5; while true; do ping -c 1 service6; sleep 2; done"'
    networks:
      - overlay_test
  service6:
    image: busybox
    command: '/bin/ash -c "sleep 6; while true; do ping -c 1 service5; sleep 2; done"'
    networks:
      - overlay_test
  service7:
    image: busybox
    command: '/bin/ash -c "sleep 7; while true; do ping -c 1 service8; sleep 2; done"'
    networks:
      - overlay_test
  service8:
    image: busybox
    command: '/bin/ash -c "sleep 8; while true; do ping -c 1 service7; sleep 2; done"'
    networks:
      - overlay_test
  service9:
    image: busybox
    command: '/bin/ash -c "sleep 9; while true; do ping -c 1 service10; sleep 2; done"'
    networks:
      - overlay_test
  service10:
    image: busybox
    command: '/bin/ash -c "while true; do ping -c 1 service9; sleep 2; done"'
    networks:
      - overlay_test